In [1]:
import pandas as pd

data = {
    "Employee": ["A","B","C","D","E","F","G","H","I","J","K"],
    "Experience_Years": [5,10,3,8,6,2,12,4,9,7,11],
    "Performance_Score": [80,90,75,85,88,70,95,78,92,86,91],
    "Satisfaction_Level": [3,4,5,2,4,3,5,4,5,3,4]
}

df = pd.DataFrame(data)

In [2]:
df["rank_score"] = (
    df["Experience_Years"]
    + df["Performance_Score"]
    + df["Satisfaction_Level"] * 5
)

In [3]:
df["rank"] = df["rank_score"].rank(ascending=False, method="dense")

In [4]:
top_10 = df.sort_values(by="rank_score", ascending=False).head(10)
top_10

,Employee,Experience_Years,Performance_Score,Satisfaction_Level,rank_score,rank
6,G,12,95,5,132,1.0
8,I,9,92,5,126,2.0
10,K,11,91,4,122,3.0
1,B,10,90,4,120,4.0
4,E,6,88,4,114,5.0
9,J,7,86,3,108,6.0
2,C,3,75,5,103,7.0
3,D,8,85,2,103,7.0
7,H,4,78,4,102,8.0
0,A,5,80,3,100,9.0

In [5]:
df

,Employee,Experience_Years,Performance_Score,Satisfaction_Level,rank_score,rank
0,A,5,80,3,100,9.0
1,B,10,90,4,120,4.0
2,C,3,75,5,103,7.0
3,D,8,85,2,103,7.0
4,E,6,88,4,114,5.0
5,F,2,70,3,87,10.0
6,G,12,95,5,132,1.0
7,H,4,78,4,102,8.0
8,I,9,92,5,126,2.0
9,J,7,86,3,108,6.0
10,K,11,91,4,122,3.0

In [6]:
top_10 = df[df["rank"] <= 10]
top_10

,Employee,Experience_Years,Performance_Score,Satisfaction_Level,rank_score,rank
0,A,5,80,3,100,9.0
1,B,10,90,4,120,4.0
2,C,3,75,5,103,7.0
3,D,8,85,2,103,7.0
4,E,6,88,4,114,5.0
5,F,2,70,3,87,10.0
6,G,12,95,5,132,1.0
7,H,4,78,4,102,8.0
8,I,9,92,5,126,2.0
9,J,7,86,3,108,6.0
10,K,11,91,4,122,3.0

In [8]:
df

,Employee,Experience_Years,Performance_Score,Satisfaction_Level,rank_score,rank
0,A,5,80,3,100,9.0
1,B,10,90,4,120,4.0
2,C,3,75,5,103,7.0
3,D,8,85,2,103,7.0
4,E,6,88,4,114,5.0
5,F,2,70,3,87,10.0
6,G,12,95,5,132,1.0
7,H,4,78,4,102,8.0
8,I,9,92,5,126,2.0
9,J,7,86,3,108,6.0
10,K,11,91,4,122,3.0

In [9]:
top_10[[
    "Employee",
    "Experience_Years",
    "Performance_Score",
    "Satisfaction_Level",
    "rank_score",
    "rank"
]]

,Employee,Experience_Years,Performance_Score,Satisfaction_Level,rank_score,rank
0,A,5,80,3,100,9.0
1,B,10,90,4,120,4.0
2,C,3,75,5,103,7.0
3,D,8,85,2,103,7.0
4,E,6,88,4,114,5.0
5,F,2,70,3,87,10.0
6,G,12,95,5,132,1.0
7,H,4,78,4,102,8.0
8,I,9,92,5,126,2.0
9,J,7,86,3,108,6.0
10,K,11,91,4,122,3.0

In [ ]:
pd.concat

In [ ]:
df.pivot

In [ ]:
df.melt

In [ ]:
df['rank'].sort_values