In [1]:
import pandas as pd

df = pd.DataFrame({
    "age": [22, 35, 45, 28, 60],
    "income": [25000, 50000, 80000, 35000, 120000],
    "family_size": [4, 3, 2, 5, 1],
    "city": [
        "Kochi",
        "Calicut",
        "Kochi",
        "Kannur",
        "Calicut"
    ]
})

In [2]:
df

   age  income  family_size     city
0   22   25000            4    Kochi
1   35   50000            3  Calicut
2   45   80000            2    Kochi
3   28   35000            5   Kannur
4   60  120000            1  Calicut

In [ ]:
df['income_per_person'] = df['income'] / df['family_size']

df

   age  income  family_size     city  income_per_person
0   22   25000            4    Kochi        6250.000000
1   35   50000            3  Calicut       16666.666667
2   45   80000            2    Kochi       40000.000000
3   28   35000            5   Kannur        7000.000000
4   60  120000            1  Calicut      120000.000000

In [5]:
bins = [0, 25, 40, 59, 100]

labels = [
    "Young",
    "Adult",
    "Middle",
    "Senior"
]

df['age_group'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels
)

In [6]:
df

   age  income  family_size     city  income_per_person age_group
0   22   25000            4    Kochi        6250.000000     Young
1   35   50000            3  Calicut       16666.666667     Adult
2   45   80000            2    Kochi       40000.000000    Middle
3   28   35000            5   Kannur        7000.000000     Adult
4   60  120000            1  Calicut      120000.000000    Senior

In [11]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(
    # drop='first',
    handle_unknown='ignore'
)

df_encoded = ohe.fit_transform(
    df[['city']]
)

df_encoded

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [12]:
df

   age  income  family_size     city  income_per_person age_group
0   22   25000            4    Kochi        6250.000000     Young
1   35   50000            3  Calicut       16666.666667     Adult
2   45   80000            2    Kochi       40000.000000    Middle
3   28   35000            5   Kannur        7000.000000     Adult
4   60  120000            1  Calicut      120000.000000    Senior

In [13]:
encoded_df = pd.DataFrame(
    df_encoded.toarray(),
    columns=ohe.get_feature_names_out(['city'])
)

df_final = pd.concat([df, encoded_df], axis=1)

df_final

,age,income,family_size,city,income_per_person,age_group,city_Calicut,city_Kannur,city_Kochi
0,22,25000,4,Kochi,6250.000000,Young,0.0,0.0,1.0
1,35,50000,3,Calicut,16666.666667,Adult,1.0,0.0,0.0
2,45,80000,2,Kochi,40000.000000,Middle,0.0,0.0,1.0
3,28,35000,5,Kannur,7000.000000,Adult,0.0,1.0,0.0
4,60,120000,1,Calicut,120000.000000,Senior,1.0,0.0,0.0

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

gh = pd.DataFrame()

numerical_features = ['age', 'income', 'family_size', 'income_per_person']

gh[numerical_features] = scaler.fit_transform(df[numerical_features])

gh

        age    income  family_size  income_per_person
0 -1.193897 -1.074384     0.707107          -0.741718
1 -0.223856 -0.348449     0.000000          -0.498244
2  0.522330  0.522673    -0.707107           0.047136
3 -0.746186 -0.784010     1.414214          -0.724188
4  1.641608  1.684169    -1.414214           1.917013