In [2]:
import pandas as pd

df = pd.DataFrame({
    "Customer": ["C1", "C2", "C3", "C4", "C5",
                 "C6", "C7", "C8", "C9", "C10"],
    "Income": [15, 18, 22, 25, 40, 45, 50, 70, 75, 80],
    "SpendingScore": [80, 75, 85, 70, 50, 55, 45, 25, 20, 30]
}
)

df

  Customer  Income  SpendingScore
0       C1      15             80
1       C2      18             75
2       C3      22             85
3       C4      25             70
4       C5      40             50
5       C6      45             55
6       C7      50             45
7       C8      70             25
8       C9      75             20
9      C10      80             30

In [3]:
from sklearn.preprocessing import StandardScaler

num = ['Income', 'SpendingScore']

scale = StandardScaler()

df[num] = scale.fit_transform(df[num])

df

  Customer    Income  SpendingScore
0       C1 -1.254014       1.184820
1       C2 -1.124288       0.961269
2       C3 -0.951321       1.408371
3       C4 -0.821595       0.737718
4       C5 -0.172967      -0.156486
5       C6  0.043242       0.067065
6       C7  0.259451      -0.380037
7       C8  1.124288      -1.274240
8       C9  1.340497      -1.497791
9      C10  1.556707      -1.050689

In [ ]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
import numpy as np

model = KMeans(
    max_iter=300
)

data = df[num]

X_train, X_test, y_train, y_test = train_test_split(
    data['Income'],
    data['SpendingScore'],
    test_size=0.2,
    random_state=42
)

AttributeError: module 'pandas' has no attribute 'toarray'

In [10]:
model.fit(X_train, y_train)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Income         10 non-null     float64
 1   SpendingScore  10 non-null     float64
dtypes: float64(2)
memory usage: 288.0 bytes

In [13]:
X_train, y_train

(5    0.043242
 0   -1.254014
 7    1.124288
 2   -0.951321
 9    1.556707
 4   -0.172967
 3   -0.821595
 6    0.259451
 Name: Income, dtype: float64,
 5    0.067065
 0    1.184820
 7   -1.274240
 2    1.408371
 9   -1.050689
 4   -0.156486
 3    0.737718
 6   -0.380037
 Name: SpendingScore, dtype: float64)