In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('/home/nihal_farooq_m/Bro_Files/16/pandas_practice_dataset.csv')
df

,order_id,customer_id,city,order_date,category,product,quantity,price,payment_mode
0,1001,279,Mumbai,2023-01-01,Clothing,Novel,3,34524,Debit Card
1,1002,262,Bangalore,2023-01-16,Clothing,Mobile,2,21079,Cash
2,1003,233,Bangalore,2023-01-31,Clothing,Shirt,1,40163,Credit Card
3,1004,228,Delhi,2023-02-15,Home,Headphones,4,3359,Debit Card
4,1005,274,Chennai,2023-03-02,Clothing,Novel,10,33804,UPI
5,1006,245,Kochi,2023-03-17,Home,Shirt,9,609,UPI
6,1007,273,Mumbai,2023-04-01,Electronics,Table,4,23361,Cash
7,1008,230,Mumbai,2023-04-16,Home,Headphones,10,43779,Debit Card
8,1009,220,Mumbai,2023-05-01,Books,Mixer,1,39307,UPI
9,1010,281,Bangalore,2023-05-16,Electronics,Mixer,8,12323,Debit Card
10,1011,286,Mumbai,2023-05-31,Clothing,Shirt,6,35938,Debit Card
11,1012,279,Chennai,2023-06-15,Electronics,Shirt,10,21254,UPI
12,1013,201,Mumbai,2023-06-30,Home,Mobile,1,16337,Cash
13,1014,212,Kochi,2023-07-15,Books,Shirt,5,6673,Debit Card
14,1015,270,Kochi,2023-07-30,Clothing,Mobile,2,49603,UPI
15,1016,205,Chennai,2023-08-14,Books,Shirt,3,40585,Cash
16,1017,285,Mumbai,2023-08-29,Books,Headphones,10,23828,Credit Card
17,1018,297,Bangalore,2023-09-13,Home,Headphones,2,33064,Debit Card
18,1019,214,Delhi,2023-09-28,Books,Shirt,7,5128,Credit Card
19,1020,276,Chennai,2023-10-13,Clothing,Headphones,3,27834,Debit Card
20,1021,293,Kochi,2023-10-28,Books,Headphones,3,18382,Cash
21,1022,219,Delhi,2023-11-12,Clothing,Shirt,2,1090,UPI
22,1023,267,Chennai,2023-11-27,Books,Novel,10,35908,Credit Card
23,1024,237,Chennai,2023-12-12,Books,Mixer,6,47641,Credit Card
24,1025,261,Mumbai,2023-12-27,Home,Mobile,9,3780,Credit Card
25,1026,225,Kochi,2024-01-11,Clothing,Novel,2,46329,UPI
26,1027,247,Mumbai,2024-01-26,Books,Shirt,4,30386,UPI
27,1028,293,Mumbai,2024-02-10,Clothing,Table,8,42540,Credit Card
28,1029,250,Bangalore,2024-02-25,Books,Laptop,2,11025,UPI
29,1030,205,Kochi,2024-03-11,Books,Table,10,44127,Credit Card
30,1031,296,Bangalore,2024-03-26,Electronics,Table,5,2037,Debit Card
31,1032,296,Kochi,2024-04-10,Home,Shirt,5,14268,Debit Card
32,1033,213,Chennai,2024-04-25,Electronics,Mobile,1,33124,Credit Card
33,1034,275,Delhi,2024-05-10,Home,Mobile,4,29016,Debit Card
34,1035,267,Bangalore,2024-05-25,Electronics,Novel,4,11726,Credit Card
35,1036,263,Chennai,2024-06-09,Electronics,Table,1,34508,Credit Card
36,1037,277,Delhi,2024-06-24,Electronics,Mobile,3,1862,UPI
37,1038,278,Delhi,2024-07-09,Home,Mobile,4,2049,Cash
38,1039,250,Mumbai,2024-07-24,Home,Headphones,5,1643,UPI
39,1040,200,Kochi,2024-08-08,Home,Laptop,4,48747,Debit Card
40,1041,212,Delhi,2024-08-23,Home,Mixer,3,40906,UPI
41,1042,255,Kochi,2024-09-07,Electronics,Headphones,1,37942,Credit Card
42,1043,248,Delhi,2024-09-22,Electronics,Shirt,1,36733,UPI
43,1044,259,Bangalore,2024-10-07,Clothing,Shirt,10,26836,Credit Card
44,1045,290,Delhi,2024-10-22,Books,Laptop,7,15468,Credit Card
45,1046,279,Bangalore,2024-11-06,Clothing,Mixer,10,29187,Cash
46,1047,274,Bangalore,2024-11-21,Clothing,Novel,10,8856,Cash
47,1048,267,Chennai,2024-12-06,Home,Mixer,7,45762,UPI
48,1049,223,Mumbai,2024-12-21,Clothing,Mobile,10,47720,Cash
49,1050,263,Mumbai,2025-01-05,Books,Table,1,40152,Credit Card

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50 non-null     int64
 1   customer_id   50 non-null     int64
 2   city          50 non-null     object
 3   order_date    50 non-null     object
 4   category      50 non-null     object
 5   product       50 non-null     object
 6   quantity      50 non-null     int64
 7   price         50 non-null     int64
 8   payment_mode  50 non-null     object
dtypes: int64(4), object(5)
memory usage: 3.6+ KB

In [5]:
df.describe()

         order_id  customer_id   quantity         price
count    50.00000     50.00000  50.000000     50.000000
mean   1025.50000    254.64000   5.060000  26046.040000
std      14.57738     29.35967   3.278937  15859.843478
min    1001.00000    200.00000   1.000000    609.000000
25%    1013.25000    228.50000   2.000000  11875.250000
50%    1025.50000    262.50000   4.000000  29101.500000
75%    1037.75000    277.75000   8.000000  39940.750000
max    1050.00000    297.00000  10.000000  49603.000000

In [6]:
df['total_amount'] = df['quantity'] * df['price']
df.head()

,order_id,customer_id,city,order_date,category,product,quantity,price,payment_mode,total_amount
0,1001,279,Mumbai,2023-01-01,Clothing,Novel,3,34524,Debit Card,103572
1,1002,262,Bangalore,2023-01-16,Clothing,Mobile,2,21079,Cash,42158
2,1003,233,Bangalore,2023-01-31,Clothing,Shirt,1,40163,Credit Card,40163
3,1004,228,Delhi,2023-02-15,Home,Headphones,4,3359,Debit Card,13436
4,1005,274,Chennai,2023-03-02,Clothing,Novel,10,33804,UPI,338040

In [8]:
print('order month and year')
df1 = df['order_date']
df1

order month and year

[0     2023-01-01
 1     2023-01-16
 2     2023-01-31
 3     2023-02-15
 4     2023-03-02
 5     2023-03-17
 6     2023-04-01
 7     2023-04-16
 8     2023-05-01
 9     2023-05-16
 10    2023-05-31
 11    2023-06-15
 12    2023-06-30
 13    2023-07-15
 14    2023-07-30
 15    2023-08-14
 16    2023-08-29
 17    2023-09-13
 18    2023-09-28
 19    2023-10-13
 20    2023-10-28
 21    2023-11-12
 22    2023-11-27
 23    2023-12-12
 24    2023-12-27
 25    2024-01-11
 26    2024-01-26
 27    2024-02-10
 28    2024-02-25
 29    2024-03-11
 30    2024-03-26
 31    2024-04-10
 32    2024-04-25
 33    2024-05-10
 34    2024-05-25
 35    2024-06-09
 36    2024-06-24
 37    2024-07-09
 38    2024-07-24
 39    2024-08-08
 40    2024-08-23
 41    2024-09-07
 42    2024-09-22
 43    2024-10-07
 44    2024-10-22
 45    2024-11-06
 46    2024-11-21
 47    2024-12-06
 48    2024-12-21
 49    2025-01-05
 Name: order_date, dtype: object]

In [9]:
# 3b

df[df['total_amount'] > 5000]

,order_id,customer_id,city,order_date,category,product,quantity,price,payment_mode,total_amount
0,1001,279,Mumbai,2023-01-01,Clothing,Novel,3,34524,Debit Card,103572
1,1002,262,Bangalore,2023-01-16,Clothing,Mobile,2,21079,Cash,42158
2,1003,233,Bangalore,2023-01-31,Clothing,Shirt,1,40163,Credit Card,40163
3,1004,228,Delhi,2023-02-15,Home,Headphones,4,3359,Debit Card,13436
4,1005,274,Chennai,2023-03-02,Clothing,Novel,10,33804,UPI,338040
5,1006,245,Kochi,2023-03-17,Home,Shirt,9,609,UPI,5481
6,1007,273,Mumbai,2023-04-01,Electronics,Table,4,23361,Cash,93444
7,1008,230,Mumbai,2023-04-16,Home,Headphones,10,43779,Debit Card,437790
8,1009,220,Mumbai,2023-05-01,Books,Mixer,1,39307,UPI,39307
9,1010,281,Bangalore,2023-05-16,Electronics,Mixer,8,12323,Debit Card,98584
10,1011,286,Mumbai,2023-05-31,Clothing,Shirt,6,35938,Debit Card,215628
11,1012,279,Chennai,2023-06-15,Electronics,Shirt,10,21254,UPI,212540
12,1013,201,Mumbai,2023-06-30,Home,Mobile,1,16337,Cash,16337
13,1014,212,Kochi,2023-07-15,Books,Shirt,5,6673,Debit Card,33365
14,1015,270,Kochi,2023-07-30,Clothing,Mobile,2,49603,UPI,99206
15,1016,205,Chennai,2023-08-14,Books,Shirt,3,40585,Cash,121755
16,1017,285,Mumbai,2023-08-29,Books,Headphones,10,23828,Credit Card,238280
17,1018,297,Bangalore,2023-09-13,Home,Headphones,2,33064,Debit Card,66128
18,1019,214,Delhi,2023-09-28,Books,Shirt,7,5128,Credit Card,35896
19,1020,276,Chennai,2023-10-13,Clothing,Headphones,3,27834,Debit Card,83502
20,1021,293,Kochi,2023-10-28,Books,Headphones,3,18382,Cash,55146
22,1023,267,Chennai,2023-11-27,Books,Novel,10,35908,Credit Card,359080
23,1024,237,Chennai,2023-12-12,Books,Mixer,6,47641,Credit Card,285846
24,1025,261,Mumbai,2023-12-27,Home,Mobile,9,3780,Credit Card,34020
25,1026,225,Kochi,2024-01-11,Clothing,Novel,2,46329,UPI,92658
26,1027,247,Mumbai,2024-01-26,Books,Shirt,4,30386,UPI,121544
27,1028,293,Mumbai,2024-02-10,Clothing,Table,8,42540,Credit Card,340320
28,1029,250,Bangalore,2024-02-25,Books,Laptop,2,11025,UPI,22050
29,1030,205,Kochi,2024-03-11,Books,Table,10,44127,Credit Card,441270
30,1031,296,Bangalore,2024-03-26,Electronics,Table,5,2037,Debit Card,10185
31,1032,296,Kochi,2024-04-10,Home,Shirt,5,14268,Debit Card,71340
32,1033,213,Chennai,2024-04-25,Electronics,Mobile,1,33124,Credit Card,33124
33,1034,275,Delhi,2024-05-10,Home,Mobile,4,29016,Debit Card,116064
34,1035,267,Bangalore,2024-05-25,Electronics,Novel,4,11726,Credit Card,46904
35,1036,263,Chennai,2024-06-09,Electronics,Table,1,34508,Credit Card,34508
36,1037,277,Delhi,2024-06-24,Electronics,Mobile,3,1862,UPI,5586
37,1038,278,Delhi,2024-07-09,Home,Mobile,4,2049,Cash,8196
38,1039,250,Mumbai,2024-07-24,Home,Headphones,5,1643,UPI,8215
39,1040,200,Kochi,2024-08-08,Home,Laptop,4,48747,Debit Card,194988
40,1041,212,Delhi,2024-08-23,Home,Mixer,3,40906,UPI,122718
41,1042,255,Kochi,2024-09-07,Electronics,Headphones,1,37942,Credit Card,37942
42,1043,248,Delhi,2024-09-22,Electronics,Shirt,1,36733,UPI,36733
43,1044,259,Bangalore,2024-10-07,Clothing,Shirt,10,26836,Credit Card,268360
44,1045,290,Delhi,2024-10-22,Books,Laptop,7,15468,Credit Card,108276
45,1046,279,Bangalore,2024-11-06,Clothing,Mixer,10,29187,Cash,291870
46,1047,274,Bangalore,2024-11-21,Clothing,Novel,10,8856,Cash,88560
47,1048,267,Chennai,2024-12-06,Home,Mixer,7,45762,UPI,320334
48,1049,223,Mumbai,2024-12-21,Clothing,Mobile,10,47720,Cash,477200
49,1050,263,Mumbai,2025-01-05,Books,Table,1,40152,Credit Card,40152